# Generated by Django 4.1.1 on 2022-09-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(default=None, max_length=100, verbose_name='Apellido')),
                ('numTelefono', models.CharField(default=None, max_length=30, verbose_name='Numero de telefono')),
                ('email', models.CharField(default=None, max_length=100, verbose_name='Email')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('estaEnDeuda', models.BooleanField(default=False, verbose_name='Deuda')),
            ],
        ),
    ]
