# Generated by Django 4.1.1 on 2022-09-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(default='', max_length=100, verbose_name='Apellido')),
                ('numTelefono', models.CharField(default='', max_length=30, verbose_name='Telefono')),
                ('email', models.CharField(default='', max_length=100, verbose_name='Email')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Activo')),
                ('estaEnDeuda', models.BooleanField(default=False, verbose_name='Esta en Deuda')),
            ],
        ),
    ]
