# Generated by Django 4.1.1 on 2022-09-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadMax', models.IntegerField(default=None)),
                ('cantidadMin', models.IntegerField(default=None)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutina.categoria')),
                ('id_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutina.ejercicio')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutina.ejercicio'),
        ),
    ]
